FROM gradle:6.0.1 as gradlebuild
COPY git-pull/ /opt/app
WORKDIR /opt/app/
RUN gradle bootJar 
RUN ls -lia /opt/app/build/libs

FROM java:8-jre-alpine
ARG BUILD_ID='<service_name>'
#ENV JAVA_OPTIONS '-Xmx600m'
ENV BUILD_ID=${BUILD_ID}
EXPOSE 9090
WORKDIR /opt/app
RUN apk update && apk add curl 
COPY --from=gradlebuild /opt/app/build/libs/<service_name>-0.0.1-SNAPSHOT.jar /opt/app/${BUILD_ID}.jar
CMD java $JAVA_OPTIONS -jar /opt/app/${BUILD_ID}.jar

